name: gh-pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"

      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Save `cache_id`
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy
        run: |
          pip install mkdocs-material
          mkdocs gh-deploy --force